//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Olympus_the_Game.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Olympus_the_Game.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap background {
            get {
                object obj = ResourceManager.GetObject("background", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;PlayField&gt;
        ///  &lt;Name&gt;Map_0&lt;/Name&gt;
        ///  &lt;Width&gt;1000&lt;/Width&gt;
        ///  &lt;Height&gt;500&lt;/Height&gt;
        ///  &lt;GameObjects&gt;
        ///    &lt;GameObject Type=&quot;GHAST&quot;&gt;
        ///      &lt;X&gt;888&lt;/X&gt;
        ///      &lt;Y&gt;0&lt;/Y&gt;
        ///      &lt;Width&gt;50&lt;/Width&gt;
        ///      &lt;Height&gt;50&lt;/Height&gt;
        ///    &lt;/GameObject&gt;
        ///    &lt;GameObject Type=&quot;GHAST&quot;&gt;
        ///      &lt;X&gt;888&lt;/X&gt;
        ///      &lt;Y&gt;50&lt;/Y&gt;
        ///      &lt;Width&gt;50&lt;/Width&gt;
        ///      &lt;Height&gt;50&lt;/Height&gt;
        ///    &lt;/GameObject&gt;
        ///    &lt;GameObject Type=&quot;GHAST&quot;&gt;
        ///      &lt;X&gt;888&lt;/X&gt;
        ///      &lt;Y&gt;100&lt;/Y&gt;
        ///      &lt;Width&gt;50&lt;/Width&gt;
        ///      &lt;H [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string beach {
            get {
                return ResourceManager.GetString("beach", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap cake {
            get {
                object obj = ResourceManager.GetObject("cake", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap cobble {
            get {
                object obj = ResourceManager.GetObject("cobble", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap cobweb {
            get {
                object obj = ResourceManager.GetObject("cobweb", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap creeper {
            get {
                object obj = ResourceManager.GetObject("creeper", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap dirt {
            get {
                object obj = ResourceManager.GetObject("dirt", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap dirt1 {
            get {
                object obj = ResourceManager.GetObject("dirt1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap explosion {
            get {
                object obj = ResourceManager.GetObject("explosion", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap fireball {
            get {
                object obj = ResourceManager.GetObject("fireball", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ghast {
            get {
                object obj = ResourceManager.GetObject("ghast", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap heartAlive {
            get {
                object obj = ResourceManager.GetObject("heartAlive", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap heartDead {
            get {
                object obj = ResourceManager.GetObject("heartDead", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;PlayField&gt;
        ///  &lt;Name&gt;Map_0&lt;/Name&gt;
        ///  &lt;Width&gt;1000&lt;/Width&gt;
        ///  &lt;Height&gt;500&lt;/Height&gt;
        ///  &lt;GameObjects&gt;
        ///    &lt;GameObject Type=&quot;START&quot;&gt;
        ///      &lt;X&gt;0&lt;/X&gt;
        ///      &lt;Y&gt;0&lt;/Y&gt;
        ///      &lt;Width&gt;150&lt;/Width&gt;
        ///      &lt;Height&gt;150&lt;/Height&gt;
        ///    &lt;/GameObject&gt;
        ///    &lt;GameObject Type=&quot;FINISH&quot;&gt;
        ///      &lt;X&gt;800&lt;/X&gt;
        ///      &lt;Y&gt;300&lt;/Y&gt;
        ///      &lt;Width&gt;150&lt;/Width&gt;
        ///      &lt;Height&gt;150&lt;/Height&gt;
        ///    &lt;/GameObject&gt;
        ///    &lt;GameObject Type=&quot;OBSTACLE&quot;&gt;
        ///      &lt;X&gt;250&lt;/X&gt;
        ///      &lt;Y&gt;250&lt;/Y&gt;
        ///      &lt;Width&gt;50&lt;/Width&gt;
        ///  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string hell {
            get {
                return ResourceManager.GetString("hell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap huis {
            get {
                object obj = ResourceManager.GetObject("huis", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap minecraft_stone_bhcmfrug {
            get {
                object obj = ResourceManager.GetObject("minecraft_stone_bhcmfrug", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Minecraftia_Regular {
            get {
                object obj = ResourceManager.GetObject("Minecraftia_Regular", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap missing {
            get {
                object obj = ResourceManager.GetObject("missing", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap player {
            get {
                object obj = ResourceManager.GetObject("player", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap player2 {
            get {
                object obj = ResourceManager.GetObject("player2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap rsz_1dragbutton {
            get {
                object obj = ResourceManager.GetObject("rsz_1dragbutton", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap rsz_arrowdown {
            get {
                object obj = ResourceManager.GetObject("rsz_arrowdown", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap rsz_arrowleft {
            get {
                object obj = ResourceManager.GetObject("rsz_arrowleft", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap rsz_arrowright {
            get {
                object obj = ResourceManager.GetObject("rsz_arrowright", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap rsz_arrowup {
            get {
                object obj = ResourceManager.GetObject("rsz_arrowup", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap spider {
            get {
                object obj = ResourceManager.GetObject("spider", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap timebomb {
            get {
                object obj = ResourceManager.GetObject("timebomb", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap tnt {
            get {
                object obj = ResourceManager.GetObject("tnt", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
